// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_starter = "CgkItqSPyeYfEAIQAg"; // <GPGSID>
        public const string achievement_being_continuous = "CgkItqSPyeYfEAIQBg"; // <GPGSID>
        public const string achievement_in_love_with_game = "CgkItqSPyeYfEAIQBw"; // <GPGSID>
        public const string achievement_pro_gamer = "CgkItqSPyeYfEAIQCQ"; // <GPGSID>
        public const string leaderboard_top_chart = "CgkItqSPyeYfEAIQAA"; // <GPGSID>
        public const string achievement_noobie = "CgkItqSPyeYfEAIQAQ"; // <GPGSID>
        public const string achievement_to_the_city = "CgkItqSPyeYfEAIQBA"; // <GPGSID>
        public const string achievement_rocking_it = "CgkItqSPyeYfEAIQCA"; // <GPGSID>
        public const string achievement_pro_starter = "CgkItqSPyeYfEAIQAw"; // <GPGSID>
        public const string achievement_to_the_country = "CgkItqSPyeYfEAIQBQ"; // <GPGSID>

}

